"""empty message

Revision ID: 00807b6a79d0
Revises: 599602e8d145
Create Date: 2016-08-02 03:45:35.139653

"""

# revision identifiers, used by Alembic.
revision = '00807b6a79d0'
down_revision = '599602e8d145'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('reference', sa.Column('name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reference', 'name')
    op.drop_column('reference', 'comment')
    ### end Alembic commands ###
