"""empty message

Revision ID: 092948543193
Revises: 136f0727752d
Create Date: 2016-08-09 17:46:02.287468

"""

# revision identifiers, used by Alembic.
revision = '092948543193'
down_revision = '136f0727752d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'scivalue_product_id_fkey', 'scivalue', type_='foreignkey')
    op.create_foreign_key(None, 'scivalue', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scivalue', type_='foreignkey')
    op.create_foreign_key(u'scivalue_product_id_fkey', 'scivalue', 'product', ['product_id'], ['id'])
    ### end Alembic commands ###
