"""empty message

Revision ID: 1ac37269e7ff
Revises: df62be078722
Create Date: 2016-08-09 16:58:15.906626

"""

# revision identifiers, used by Alembic.
revision = '1ac37269e7ff'
down_revision = 'df62be078722'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'prod_process_co2_association_process_id_fkey', 'prod_process_co2_association', type_='foreignkey')
    op.create_foreign_key(None, 'prod_process_co2_association', 'process', ['process_id'], ['id'], ondelete='SET NULL')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prod_process_co2_association', type_='foreignkey')
    op.create_foreign_key(u'prod_process_co2_association_process_id_fkey', 'prod_process_co2_association', 'process', ['process_id'], ['id'], ondelete=u'CASCADE')
    ### end Alembic commands ###
