"""empty message

Revision ID: 39b671ba4005
Revises: 61150ffdf90e
Create Date: 2016-09-22 11:42:40.546787

"""

# revision identifiers, used by Alembic.
revision = '39b671ba4005'
down_revision = '61150ffdf90e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('type', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process', 'type')
    ### end Alembic commands ###
