"""empty message

Revision ID: 3f9ba5764468
Revises: bc59d30385d7
Create Date: 2016-08-10 10:10:23.657626

"""

# revision identifiers, used by Alembic.
revision = '3f9ba5764468'
down_revision = 'bc59d30385d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scivalue', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scivalue', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scivalue', type_='foreignkey')
    op.drop_column('scivalue', 'product_id')
    ### end Alembic commands ###
