"""empty message

Revision ID: 43fd8c6dfbf2
Revises: 7b7c5c2afe52
Create Date: 2016-08-10 00:32:25.318805

"""

# revision identifiers, used by Alembic.
revision = '43fd8c6dfbf2'
down_revision = '7b7c5c2afe52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'foodwaste_product_id_fkey', 'foodwaste', type_='foreignkey')
    op.drop_column('foodwaste', 'product_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodwaste', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'foodwaste_product_id_fkey', 'foodwaste', 'product', ['product_id'], ['id'])
    ### end Alembic commands ###
