"""empty message

Revision ID: 574cfcd5eb17
Revises: b507616e75f0
Create Date: 2016-09-21 22:44:58.036032

"""

# revision identifiers, used by Alembic.
revision = '574cfcd5eb17'
down_revision = 'b507616e75f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('endOfLocalSeason', sa.String(), nullable=True))
    op.add_column('product', sa.Column('startOfLocalSeason', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'startOfLocalSeason')
    op.drop_column('product', 'endOfLocalSeason')
    ### end Alembic commands ###
