"""empty message

Revision ID: 599602e8d145
Revises: c531833fb3ea
Create Date: 2016-08-02 03:38:48.349088

"""

# revision identifiers, used by Alembic.
revision = '599602e8d145'
down_revision = 'c531833fb3ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scivalue', sa.Column('confidenceInterval', sa.Integer(), nullable=True))
    op.add_column('scivalue', sa.Column('unit', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scivalue', 'unit')
    op.drop_column('scivalue', 'confidenceInterval')
    ### end Alembic commands ###
