"""empty message

Revision ID: 61150ffdf90e
Revises: 6a6005dc2d4c
Create Date: 2016-09-22 00:24:26.363101

"""

# revision identifiers, used by Alembic.
revision = '61150ffdf90e'
down_revision = '6a6005dc2d4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scivalue', sa.Column('amount', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scivalue', 'amount')
    ### end Alembic commands ###
