"""empty message

Revision ID: 65853cb99c18
Revises: None
Create Date: 2016-07-26 12:28:54.841539

"""

# revision identifiers, used by Alembic.
revision = '65853cb99c18'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('co2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('co2_prod_association',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('co2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['co2_id'], ['co2.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'co2_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('co2_prod_association')
    op.drop_table('co2')
    ### end Alembic commands ###
