"""empty message

Revision ID: 6a6005dc2d4c
Revises: 574cfcd5eb17
Create Date: 2016-09-22 00:24:15.999102

"""

# revision identifiers, used by Alembic.
revision = '6a6005dc2d4c'
down_revision = '574cfcd5eb17'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scivalue', 'amount')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scivalue', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
