"""empty message

Revision ID: 71ea99d099f6
Revises: f7a0c20d627c
Create Date: 2016-08-18 00:55:14.306646

"""

# revision identifiers, used by Alembic.
revision = '71ea99d099f6'
down_revision = 'f7a0c20d627c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'location_prod_association_location_id_fkey', 'location_prod_association', type_='foreignkey')
    op.drop_constraint(u'location_prod_association_product_id_fkey', 'location_prod_association', type_='foreignkey')
    op.create_foreign_key(None, 'location_prod_association', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'location_prod_association', 'location', ['location_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location_prod_association', type_='foreignkey')
    op.drop_constraint(None, 'location_prod_association', type_='foreignkey')
    op.create_foreign_key(u'location_prod_association_product_id_fkey', 'location_prod_association', 'product', ['product_id'], ['id'])
    op.create_foreign_key(u'location_prod_association_location_id_fkey', 'location_prod_association', 'location', ['location_id'], ['id'])
    ### end Alembic commands ###
