"""empty message

Revision ID: 7b7c5c2afe52
Revises: 90b6f453bce4
Create Date: 2016-08-10 00:31:29.654515

"""

# revision identifiers, used by Alembic.
revision = '7b7c5c2afe52'
down_revision = '90b6f453bce4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'co2_product_id_fkey', 'co2', type_='foreignkey')
    op.drop_column('co2', 'product_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('co2', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'co2_product_id_fkey', 'co2', 'product', ['product_id'], ['id'])
    ### end Alembic commands ###
