"""empty message

Revision ID: 7be395358d27
Revises: 3f9ba5764468
Create Date: 2016-08-10 10:14:48.883501

"""

# revision identifiers, used by Alembic.
revision = '7be395358d27'
down_revision = '3f9ba5764468'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'scivalue_product_id_fkey', 'scivalue', type_='foreignkey')
    op.drop_column('scivalue', 'product_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scivalue', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'scivalue_product_id_fkey', 'scivalue', 'product', ['product_id'], ['id'], ondelete=u'CASCADE')
    ### end Alembic commands ###
