"""empty message

Revision ID: 8bc97a172de1
Revises: 9ca52745fa9e
Create Date: 2016-09-21 21:46:03.095456

"""

# revision identifiers, used by Alembic.
revision = '8bc97a172de1'
down_revision = '9ca52745fa9e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'euro4Id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('euro4Id', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
