"""empty message

Revision ID: a209d3206cd7
Revises: 48471116cc35
Create Date: 2016-08-10 09:44:55.352579

"""

# revision identifiers, used by Alembic.
revision = 'a209d3206cd7'
down_revision = '48471116cc35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prod_nutrient_association', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prod_nutrient_association', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
