"""empty message

Revision ID: a2f219ffa1f2
Revises: 7ab3e266f711
Create Date: 2016-08-09 22:03:30.019854

"""

# revision identifiers, used by Alembic.
revision = 'a2f219ffa1f2'
down_revision = '7ab3e266f711'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'scivalue_product_id_fkey', 'scivalue', type_='foreignkey')
    op.drop_column('scivalue', 'product_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scivalue', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'scivalue_product_id_fkey', 'scivalue', 'product', ['product_id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    ### end Alembic commands ###
