"""empty message

Revision ID: a3143946c713
Revises: 822560cb0074
Create Date: 2016-08-09 23:31:06.814361

"""

# revision identifiers, used by Alembic.
revision = 'a3143946c713'
down_revision = '822560cb0074'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'co2_id_fkey', 'co2', type_='foreignkey')
    op.create_foreign_key(None, 'co2', 'scivalue', ['id'], ['id'])
    op.drop_constraint(u'density_id_fkey', 'density', type_='foreignkey')
    op.create_foreign_key(None, 'density', 'scivalue', ['id'], ['id'])
    op.drop_constraint(u'edb_product_id_fkey', 'edb_product', type_='foreignkey')
    op.create_foreign_key(None, 'edb_product', 'product', ['id'], ['id'])
    op.drop_constraint(u'foodwaste_id_fkey', 'foodwaste', type_='foreignkey')
    op.create_foreign_key(None, 'foodwaste', 'scivalue', ['id'], ['id'])
    op.drop_constraint(u'location_prod_association_product_id_fkey', 'location_prod_association', type_='foreignkey')
    op.create_foreign_key(None, 'location_prod_association', 'product', ['product_id'], ['id'])
    op.drop_constraint(u'prod_allergene_association_id_fkey', 'prod_allergene_association', type_='foreignkey')
    op.create_foreign_key(None, 'prod_allergene_association', 'scivalue', ['id'], ['id'])
    op.drop_constraint(u'prod_nutrient_association_id_fkey', 'prod_nutrient_association', type_='foreignkey')
    op.drop_constraint(u'prod_nutrient_association_product_id_fkey', 'prod_nutrient_association', type_='foreignkey')
    op.create_foreign_key(None, 'prod_nutrient_association', 'scivalue', ['id'], ['id'])
    op.create_foreign_key(None, 'prod_nutrient_association', 'product', ['product_id'], ['id'])
    op.drop_constraint(u'prod_process_association_product_id_fkey', 'prod_process_association', type_='foreignkey')
    op.drop_constraint(u'prod_process_association_id_fkey', 'prod_process_association', type_='foreignkey')
    op.create_foreign_key(None, 'prod_process_association', 'scivalue', ['id'], ['id'])
    op.create_foreign_key(None, 'prod_process_association', 'product', ['product_id'], ['id'])
    op.drop_constraint(u'prod_process_co2_association_id_fkey', 'prod_process_co2_association', type_='foreignkey')
    op.create_foreign_key(None, 'prod_process_co2_association', 'scivalue', ['id'], ['id'])
    op.drop_constraint(u'synonym_prod_association_product_id_fkey', 'synonym_prod_association', type_='foreignkey')
    op.create_foreign_key(None, 'synonym_prod_association', 'product', ['product_id'], ['id'])
    op.drop_constraint(u'tag_prod_association_tag_name_fkey', 'tag_prod_association', type_='foreignkey')
    op.drop_constraint(u'tag_prod_association_product_id_fkey', 'tag_prod_association', type_='foreignkey')
    op.create_foreign_key(None, 'tag_prod_association', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'tag_prod_association', 'tag', ['tag_name'], ['name'])
    op.drop_constraint(u'template_id_fkey', 'template', type_='foreignkey')
    op.create_foreign_key(None, 'template', 'product', ['id'], ['id'])
    op.drop_constraint(u'unit_weight_id_fkey', 'unit_weight', type_='foreignkey')
    op.create_foreign_key(None, 'unit_weight', 'scivalue', ['id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit_weight', type_='foreignkey')
    op.create_foreign_key(u'unit_weight_id_fkey', 'unit_weight', 'scivalue', ['id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.drop_constraint(None, 'template', type_='foreignkey')
    op.create_foreign_key(u'template_id_fkey', 'template', 'product', ['id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'tag_prod_association', type_='foreignkey')
    op.drop_constraint(None, 'tag_prod_association', type_='foreignkey')
    op.create_foreign_key(u'tag_prod_association_product_id_fkey', 'tag_prod_association', 'product', ['product_id'], ['id'], ondelete=u'CASCADE')
    op.create_foreign_key(u'tag_prod_association_tag_name_fkey', 'tag_prod_association', 'tag', ['tag_name'], ['name'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'synonym_prod_association', type_='foreignkey')
    op.create_foreign_key(u'synonym_prod_association_product_id_fkey', 'synonym_prod_association', 'product', ['product_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'prod_process_co2_association', type_='foreignkey')
    op.create_foreign_key(u'prod_process_co2_association_id_fkey', 'prod_process_co2_association', 'scivalue', ['id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.drop_constraint(None, 'prod_process_association', type_='foreignkey')
    op.drop_constraint(None, 'prod_process_association', type_='foreignkey')
    op.create_foreign_key(u'prod_process_association_id_fkey', 'prod_process_association', 'scivalue', ['id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.create_foreign_key(u'prod_process_association_product_id_fkey', 'prod_process_association', 'product', ['product_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'prod_nutrient_association', type_='foreignkey')
    op.drop_constraint(None, 'prod_nutrient_association', type_='foreignkey')
    op.create_foreign_key(u'prod_nutrient_association_product_id_fkey', 'prod_nutrient_association', 'product', ['product_id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.create_foreign_key(u'prod_nutrient_association_id_fkey', 'prod_nutrient_association', 'scivalue', ['id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.drop_constraint(None, 'prod_allergene_association', type_='foreignkey')
    op.create_foreign_key(u'prod_allergene_association_id_fkey', 'prod_allergene_association', 'scivalue', ['id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.drop_constraint(None, 'location_prod_association', type_='foreignkey')
    op.create_foreign_key(u'location_prod_association_product_id_fkey', 'location_prod_association', 'product', ['product_id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.drop_constraint(None, 'foodwaste', type_='foreignkey')
    op.create_foreign_key(u'foodwaste_id_fkey', 'foodwaste', 'scivalue', ['id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.drop_constraint(None, 'edb_product', type_='foreignkey')
    op.create_foreign_key(u'edb_product_id_fkey', 'edb_product', 'product', ['id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'density', type_='foreignkey')
    op.create_foreign_key(u'density_id_fkey', 'density', 'scivalue', ['id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.drop_constraint(None, 'co2', type_='foreignkey')
    op.create_foreign_key(u'co2_id_fkey', 'co2', 'scivalue', ['id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    ### end Alembic commands ###
