"""empty message

Revision ID: a42d76603624
Revises: e1a7e2b10050
Create Date: 2016-08-09 17:53:13.488666

"""

# revision identifiers, used by Alembic.
revision = 'a42d76603624'
down_revision = 'e1a7e2b10050'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'scivalue_product_id_fkey', 'scivalue', type_='foreignkey')
    op.create_foreign_key(None, 'scivalue', 'product', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scivalue', type_='foreignkey')
    op.create_foreign_key(u'scivalue_product_id_fkey', 'scivalue', 'product', ['product_id'], ['id'], ondelete=u'CASCADE')
    ### end Alembic commands ###
