"""empty message

Revision ID: b4f82c548241
Revises: 00807b6a79d0
Create Date: 2016-08-04 12:34:11.364677

"""

# revision identifiers, used by Alembic.
revision = 'b4f82c548241'
down_revision = '00807b6a79d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foodwaste_field',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foodwaste_field')
    ### end Alembic commands ###
