"""empty message

Revision ID: b507616e75f0
Revises: af5c96902a03
Create Date: 2016-09-21 22:44:46.995286

"""

# revision identifiers, used by Alembic.
revision = 'b507616e75f0'
down_revision = 'af5c96902a03'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'endOfLocalSeason')
    op.drop_column('product', 'startOfLocalSeason')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('startOfLocalSeason', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('endOfLocalSeason', sa.DATE(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
