"""empty message

Revision ID: b51fe1d152cf
Revises: 7be395358d27
Create Date: 2016-08-10 10:33:20.572946

"""

# revision identifiers, used by Alembic.
revision = 'b51fe1d152cf'
down_revision = '7be395358d27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'synonym_prod_association_product_id_fkey', 'synonym_prod_association', type_='foreignkey')
    op.create_foreign_key(None, 'synonym_prod_association', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'tag_prod_association_product_id_fkey', 'tag_prod_association', type_='foreignkey')
    op.create_foreign_key(None, 'tag_prod_association', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_prod_association', type_='foreignkey')
    op.create_foreign_key(u'tag_prod_association_product_id_fkey', 'tag_prod_association', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'synonym_prod_association', type_='foreignkey')
    op.create_foreign_key(u'synonym_prod_association_product_id_fkey', 'synonym_prod_association', 'product', ['product_id'], ['id'])
    ### end Alembic commands ###
