"""empty message

Revision ID: b79fdb768212
Revises: dd58d8eab0d6
Create Date: 2016-09-19 23:25:09.393811

"""

# revision identifiers, used by Alembic.
revision = 'b79fdb768212'
down_revision = 'dd58d8eab0d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prod_process_nutrient_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('nutrient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['scivalue.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrient.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('prod_process_association')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prod_process_association',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('process_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nutrient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], [u'scivalue.id'], name=u'prod_process_association_id_fkey', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['nutrient_id'], [u'nutrient.id'], name=u'prod_process_association_nutrient_id_fkey'),
    sa.ForeignKeyConstraint(['process_id'], [u'process.id'], name=u'prod_process_association_process_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'prod_process_association_pkey')
    )
    op.drop_table('prod_process_nutrient_association')
    ### end Alembic commands ###
