"""empty message

Revision ID: bc59d30385d7
Revises: a209d3206cd7
Create Date: 2016-08-10 09:49:04.194410

"""

# revision identifiers, used by Alembic.
revision = 'bc59d30385d7'
down_revision = 'a209d3206cd7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prod_nutrient_association', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prod_nutrient_association', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
