"""empty message

Revision ID: cccaa431f061
Revises: 2018d552dff6
Create Date: 2016-08-14 10:57:21.439169

"""

# revision identifiers, used by Alembic.
revision = 'cccaa431f061'
down_revision = '2018d552dff6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allergene', sa.Column('abbreviation', sa.String(), nullable=True))
    op.drop_column('allergene', 'shortname')
    op.add_column('nutrient', sa.Column('abbreviation', sa.String(), nullable=True))
    op.drop_column('nutrient', 'shortname')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrient', sa.Column('shortname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('nutrient', 'abbreviation')
    op.add_column('allergene', sa.Column('shortname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('allergene', 'abbreviation')
    ### end Alembic commands ###
