"""empty message

Revision ID: dd58d8eab0d6
Revises: e3c68e835c84
Create Date: 2016-08-24 15:15:07.404739

"""

# revision identifiers, used by Alembic.
revision = 'dd58d8eab0d6'
down_revision = 'e3c68e835c84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'prod_allergene_association_allergene_id_fkey', 'prod_allergene_association', type_='foreignkey')
    op.create_foreign_key(None, 'prod_allergene_association', 'allergene', ['allergene_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(u'scivalue_reference_id_fkey', 'scivalue', type_='foreignkey')
    op.create_foreign_key(None, 'scivalue', 'reference', ['reference_id'], ['id'], ondelete='SET NULL')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scivalue', type_='foreignkey')
    op.create_foreign_key(u'scivalue_reference_id_fkey', 'scivalue', 'reference', ['reference_id'], ['id'])
    op.drop_constraint(None, 'prod_allergene_association', type_='foreignkey')
    op.create_foreign_key(u'prod_allergene_association_allergene_id_fkey', 'prod_allergene_association', 'allergene', ['allergene_id'], ['id'])
    ### end Alembic commands ###
