"""empty message

Revision ID: e1a7e2b10050
Revises: 092948543193
Create Date: 2016-08-09 17:51:00.594482

"""

# revision identifiers, used by Alembic.
revision = 'e1a7e2b10050'
down_revision = '092948543193'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'co2_id_fkey', 'co2', type_='foreignkey')
    op.create_foreign_key(None, 'co2', 'scivalue', ['id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(u'density_id_fkey', 'density', type_='foreignkey')
    op.create_foreign_key(None, 'density', 'scivalue', ['id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(u'foodwaste_id_fkey', 'foodwaste', type_='foreignkey')
    op.create_foreign_key(None, 'foodwaste', 'scivalue', ['id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(u'prod_allergene_association_id_fkey', 'prod_allergene_association', type_='foreignkey')
    op.create_foreign_key(None, 'prod_allergene_association', 'scivalue', ['id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(u'prod_nutrient_association_id_fkey', 'prod_nutrient_association', type_='foreignkey')
    op.create_foreign_key(None, 'prod_nutrient_association', 'scivalue', ['id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(u'prod_process_association_id_fkey', 'prod_process_association', type_='foreignkey')
    op.create_foreign_key(None, 'prod_process_association', 'scivalue', ['id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(u'prod_process_co2_association_id_fkey', 'prod_process_co2_association', type_='foreignkey')
    op.create_foreign_key(None, 'prod_process_co2_association', 'scivalue', ['id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(u'unit_weight_id_fkey', 'unit_weight', type_='foreignkey')
    op.create_foreign_key(None, 'unit_weight', 'scivalue', ['id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit_weight', type_='foreignkey')
    op.create_foreign_key(u'unit_weight_id_fkey', 'unit_weight', 'scivalue', ['id'], ['id'])
    op.drop_constraint(None, 'prod_process_co2_association', type_='foreignkey')
    op.create_foreign_key(u'prod_process_co2_association_id_fkey', 'prod_process_co2_association', 'scivalue', ['id'], ['id'])
    op.drop_constraint(None, 'prod_process_association', type_='foreignkey')
    op.create_foreign_key(u'prod_process_association_id_fkey', 'prod_process_association', 'scivalue', ['id'], ['id'])
    op.drop_constraint(None, 'prod_nutrient_association', type_='foreignkey')
    op.create_foreign_key(u'prod_nutrient_association_id_fkey', 'prod_nutrient_association', 'scivalue', ['id'], ['id'])
    op.drop_constraint(None, 'prod_allergene_association', type_='foreignkey')
    op.create_foreign_key(u'prod_allergene_association_id_fkey', 'prod_allergene_association', 'scivalue', ['id'], ['id'])
    op.drop_constraint(None, 'foodwaste', type_='foreignkey')
    op.create_foreign_key(u'foodwaste_id_fkey', 'foodwaste', 'scivalue', ['id'], ['id'])
    op.drop_constraint(None, 'density', type_='foreignkey')
    op.create_foreign_key(u'density_id_fkey', 'density', 'scivalue', ['id'], ['id'])
    op.drop_constraint(None, 'co2', type_='foreignkey')
    op.create_foreign_key(u'co2_id_fkey', 'co2', 'scivalue', ['id'], ['id'])
    ### end Alembic commands ###
