"""empty message

Revision ID: f18180ede802
Revises: b4f82c548241
Create Date: 2016-08-04 13:30:05.947108

"""

# revision identifiers, used by Alembic.
revision = 'f18180ede802'
down_revision = 'b4f82c548241'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodwaste', sa.Column('field_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'foodwaste', 'foodwaste_field', ['field_id'], ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'foodwaste', type_='foreignkey')
    op.drop_column('foodwaste', 'field_id')
    ### end Alembic commands ###
